services:
  frontend:
    image: ghcr.io/graderd/grade-list-frontend:${FRONTEND_VERSION:-v1.0.0}
    container_name: grade-list-frontend
    restart: unless-stopped

    environment:
      API_URL: ${API_URL:-http://api.home}

    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
